### PR TITLE
Consistent usage of parameter null check

### PR DESCRIPTION
**Pull request by PoisonedYouth**
While trying to understand functionality of project, fixed inconsistent usage of parameter null check

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@PoisonedYouth Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-client&pullRequestId=22)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-client&pullRequestId=22) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@PoisonedYouth Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-client&pullRequestId=22)!

**Comment by PoisonedYouth** [comment]
Interesting approach. Thanks for feedback.

I've seen the yesterday session on W-Jax and very interested in supporting this project.

**Comment by nebhale** [comment]
Given how simple and stateless `r2dbc-client` is, I can see how the direct assignment seems like an aberration.  If you take a look at the `r2dbc-postgresql`, which has a vastly larger number of null checks generally, I think you’ll find that non-assignment is the aberration more broadly across the R2DBC project.

It’s great to hear that you’re interested in the project and looking to contribute.  While this PR didn’t work out, I look forward to seeing furture contributions from you.

**Pull request closed without merging**
